<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CiudadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ciudades')->insert([

        ["estado_id" => 1, "municipio_id" => 1, "nombre"=> 'Caracas', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 2, "nombre"=>'Chacao', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 3, "nombre"=>'Nuestra Señora Del Rosario de Baruta', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 3, "nombre"=>'Las Minas de Baruta', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 4, "nombre"=>'Petare', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 4, "nombre"=>'Fila de Mariches', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 4, "nombre"=>'Los Dos Caminos', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 4, "nombre"=>'Caucaguita', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 4, "nombre"=>'La Dolorita', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 5, "nombre"=>'La Dolorita', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 5, "nombre"=>'El Hatillo', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 6, "nombre"=>'Los Teques', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 6, "nombre"=>'El Jarillo', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 6, "nombre"=>'Paracotos', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 6, "nombre"=>'San Pedro', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 6, "nombre"=>'Altagracia', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 6, "nombre"=>'Tácata', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 7, "nombre"=>'Carrizal', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 7, "nombre"=>'San Diego', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 8, "nombre"=>'San Antonio de Los Altos', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 9, "nombre"=>'Ocumare del Tuy', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 9, "nombre"=>'La Democracia', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 9, "nombre"=>'Santa Bárbara', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 10, "nombre"=>'Charallave', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 10, "nombre"=>'Las Brisas', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 11, "nombre"=>'Cúa', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 11, "nombre"=>'Nueva Cúa', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 12, "nombre"=>'San Francisco de Yare', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 12, "nombre"=>'San Antonio de Yare', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 13, "nombre"=>'Santa Lucía', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 14, "nombre"=>'Santa Teresa del Tuy', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 14, "nombre"=>'El Cartanal', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 15, "nombre"=>'Guarenas', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 16, "nombre"=>'Guatire', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 16, "nombre"=>'Araira', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 17, "nombre"=>'Mamporal', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 18, "nombre"=>'Higuerote', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 18, "nombre"=>'Curiepe', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 18, "nombre"=>'Tacarigua de Mamporal', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 19, "nombre"=>'San José de Barlovento', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 19, "nombre"=>'Cumbo', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 20, "nombre"=>'Río Chico', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 20, "nombre"=>'Tacarigua de La Laguna', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 20, "nombre"=>'Paparo', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 20, "nombre"=>'El Guapo', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 20, "nombre"=>'San Fernando', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 21, "nombre"=>'Cúpira', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 22, "nombre"=>'Caucagua', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 22, "nombre"=>'Marizapa', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 22, "nombre"=>'Aragüita', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 22, "nombre"=>'Tapipa', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 22, "nombre"=>'Capaya', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 22, "nombre"=>'El Café', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 22, "nombre"=>'Panaquire', "created_at" => now()],
        ["estado_id" => 2, "municipio_id" => 22, "nombre"=>' El Clavo', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 23, "nombre"=>'Barinas', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 23, "nombre"=>'Quebrada Seca', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 23, "nombre"=>'Santa Inés', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 23, "nombre"=>'Santa Lucía', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 23, "nombre"=>'Torunos', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 23, "nombre"=>'La Caramuca', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 23, "nombre"=>'El Corozo', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 23, "nombre"=>'La Mula', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 23, "nombre"=>'San Silvestre', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 24, "nombre"=>'Sabaneta', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 24, "nombre"=>'Veguitas', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 25, "nombre"=>'Ciudad de Nutrias', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 25, "nombre"=>'El Regalo', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 25, "nombre"=>'Puerto de Nutrias', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 25, "nombre"=>'Santa Catalina', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 26, "nombre"=>'Socopó', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 26, "nombre"=>'Bum-Bum', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 26, "nombre"=>'Chameta', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 27, "nombre"=>'Arismendi', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 27, "nombre"=>'Guadarrama', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 27, "nombre"=>'La Unión', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 27, "nombre"=>'San Antonio', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 28, "nombre"=>'Libertad', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 28, "nombre"=>'Dolores', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 28, "nombre"=>'Mijagual', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 28, "nombre"=>'Santa Rosa', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 29, "nombre"=>'Barinitas', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 29, "nombre"=>'Altamira', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 29, "nombre"=>'Calderas', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 30, "nombre"=>'Barrancas', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 30, "nombre"=>'La Yuca', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 30, "nombre"=>'Masparrito', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 31, "nombre"=>'Santa Bárbara', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 31, "nombre"=>'Pedraza La Vieja', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 31, "nombre"=>'Capitanejo', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 31, "nombre"=>'Punta de Piedra', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 32, "nombre"=>'El Cantón', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 32, "nombre"=>'Santa Cruz de Guacas', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 32, "nombre"=>'Puerto Vivas', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 33, "nombre"=>'Obispos', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 33, "nombre"=>'El Real', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 33, "nombre"=>'La Luz', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 33, "nombre"=>'Los Guasimitos', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 34, "nombre"=>'Ciudad Bolivia', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 34, "nombre"=>'Maporal', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 34, "nombre"=>'Curbatí', "created_at" => now()],
        ["estado_id" => 3, "municipio_id" => 34, "nombre"=>'San Rafael de Canagua', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 35, "nombre"=>'Matríz', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 35, "nombre"=>'San Lázaro', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 35, "nombre"=>'Chiquinquirá', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 35, "nombre"=>'Santa Rosa', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 35, "nombre"=>'La Plazuela', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 35, "nombre"=>'San Jacinto', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 35, "nombre"=>'Tres Esquinas', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 36, "nombre"=>'Juan Ignacio Montilla', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 36, "nombre"=>'La Beatríz', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 36, "nombre"=>'Mercedes Díaz', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 36, "nombre"=>'San Luis', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 36, "nombre"=>'La Puerta', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 36, "nombre"=>'Mendoza', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 37, "nombre"=>'Escuque', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 37, "nombre"=>'El Alto', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 37, "nombre"=>'Sabana Libre', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 37, "nombre"=>'La Mata', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 38, "nombre"=>'Motatán', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 38, "nombre"=>'El Baño', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 38, "nombre"=>'Jalisco', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 39, "nombre"=>'Pampanito', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 39, "nombre"=>'La Concepción', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 39, "nombre"=>'Pampanito ll', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 40, "nombre"=>'Betijoque', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 40, "nombre"=>'Las Rurales', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 40, "nombre"=>'Los Cedros', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 40, "nombre"=>'Isnotú', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 41, "nombre"=>'Carvajal', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 41, "nombre"=>'La Cejita', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 41, "nombre"=>'Campo Alegre', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 41, "nombre"=>'Las Mesetas', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'Boconó', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'El Carmen', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'Mosquey', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'Batatal', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'Burbusay', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'Las Mesitas', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'Guaramacal', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'Vega de Guaramacal', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'Niquitao', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'San Rafael', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'San Miguel', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 42, "nombre"=>'Tostós', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 43, "nombre"=>'Campo Elías', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 43, "nombre"=>'Las Quebradas', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 44, "nombre"=>'Pampán', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 44, "nombre"=>'Flor de Patria', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 44, "nombre"=>'Monay', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 44, "nombre"=>'Santa Ana', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 45, "nombre"=>'El Paradero', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 45, "nombre"=>'La Placita', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 45, "nombre"=>'Los Caprichos', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 46, "nombre"=>'Chejendé', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 46, "nombre"=>'Minas', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 46, "nombre"=>'Bolivia', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 46, "nombre"=>'Torococo', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 46, "nombre"=>'Mitón', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 46, "nombre"=>'Sabana Grande', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 46, "nombre"=>'Las Llanadas', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 47, "nombre"=>'Carache', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 47, "nombre"=>'Cuicas', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 47, "nombre"=>'La Concepción', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 47, "nombre"=>'El Zapatero', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 47, "nombre"=>'La Cuchilla', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 48, "nombre"=>'Sabana de Mendoza', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 48, "nombre"=>'El Paraíso', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 48, "nombre"=>'Junín', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 48, "nombre"=>'Valmore Rodríguez', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 49, "nombre"=>'Sabana Grande', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 49, "nombre"=>'Altamira de Caús', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 49, "nombre"=>'Granados', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 50, "nombre"=>'El Dividive', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 50, "nombre"=>'Agua Santa', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 50, "nombre"=>'Agua Caliente', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 50, "nombre"=>'El Cenizo', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 50, "nombre"=>'Valerita', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 51, "nombre"=>'Santa Isabel', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 51, "nombre"=>'Araguaney', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 51, "nombre"=>'El Jagüito', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 51, "nombre"=>'El Gallo', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 52, "nombre"=>'Monte Carmelo', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 52, "nombre"=>'Buena Vista', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 52, "nombre"=>'Casa de Tabla', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 53, "nombre"=>'La Quebrada', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 53, "nombre"=>'Cabimbú', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 53, "nombre"=>'Jajó', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 53, "nombre"=>'La Mesa de Esnujaque', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 53, "nombre"=>'Santiago', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 53, "nombre"=>'Tuñame', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 54, "nombre"=>'Santa Apolonia', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 54, "nombre"=>'Zona Rica', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 54, "nombre"=>'Tres de Febrero', "created_at" => now()],
        ["estado_id" => 4, "municipio_id" => 54, "nombre"=>'La Ceiba', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 55, "nombre"=>'Mérida', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 55, "nombre"=>'El Morro', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 55, "nombre"=>'Los Nevados', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 56, "nombre"=>'El Vígia', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 56, "nombre"=>'El Vigía', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 56, "nombre"=>'La Palmita', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 56, "nombre"=>'Mucujepe', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 56, "nombre"=>'Los Naranjos', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 56, "nombre"=>'La Blanca (12 de Octubre)', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 57, "nombre"=>'La Azulita', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 58, "nombre"=>'Santa María de Caparo', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 59, "nombre"=>'Pueblo Llano', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 60, "nombre"=>'Mucuchíes', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 60, "nombre"=>'La Toma', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 60, "nombre"=>'San Rafael', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 60, "nombre"=>'Cacute', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 60, "nombre"=>'Macurubá', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 61, "nombre"=>'Bailadores', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 61, "nombre"=>'La Playa', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 62, "nombre"=>'Tabay', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 63, "nombre"=>'Tovar', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 64, "nombre"=>'Mesa de Quintero', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 64, "nombre"=>'Río Negro', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 65, "nombre"=>'Lagunillas', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 65, "nombre"=>'Chiguará', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 65, "nombre"=>'Estánquez', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 65, "nombre"=>'La Trampa', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 65, "nombre"=>'Pueblo Nuevo del Sur', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 65, "nombre"=>'San Juan', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 66, "nombre"=>'Capital Zea', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 66, "nombre"=>'Caño El Tigre', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 67, "nombre"=>'Santa Cruz de Mora', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 67, "nombre"=>'Mesa Bolívar', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 67, "nombre"=>'Mesa de Las Palmas', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 68, "nombre"=>'Aricagua', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 68, "nombre"=>'Campo Elías', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 69, "nombre"=>'Canaguá', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 69, "nombre"=>'Capurí', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 69, "nombre"=>'Chacantá', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 69, "nombre"=>'El Molino', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 69, "nombre"=>'Guaimaral', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 69, "nombre"=>'Mucuchachí', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 69, "nombre"=>'Mucutuy', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 70, "nombre"=>'Ejido', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 70, "nombre"=>'Acequias', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 70, "nombre"=>'Jají', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 70, "nombre"=>'La Mesa', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 70, "nombre"=>'San José', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 71, "nombre"=>'Santa Elena de Arenales', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 71, "nombre"=>'Guayabones', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 71, "nombre"=>'San Rafael de Alcázar', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 72, "nombre"=>'Tucaní', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 72, "nombre"=>'El Pinar', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 73, "nombre"=>'Santo Domingo', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 73, "nombre"=>'Las Piedras', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 74, "nombre"=>'Arapuey', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 74, "nombre"=>'San José de Palmira', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 75, "nombre"=>'San José de Palmira', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 75, "nombre"=>'Torondoy', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 76, "nombre"=>'Nueva Bolivia', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 76, "nombre"=>'Palmarito', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 76, "nombre"=>'Las Virtudes', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 77, "nombre"=>'Timotes', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 77, "nombre"=>'Chachopo', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 77, "nombre"=>'La Venta', "created_at" => now()],
        ["estado_id" => 5, "municipio_id" => 77, "nombre"=>'Piñango', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 78, "nombre"=>'San Cristóbal', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 78, "nombre"=>'San Cristobál', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 78, "nombre"=>'Macanillo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 79, "nombre"=>'Táriba', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 79, "nombre"=>'La Florida', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 79, "nombre"=>'Palo Gordo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 80, "nombre"=>'Cordero', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 81, "nombre"=>'Palmira', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 82, "nombre"=>'Queniquea', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 82, "nombre"=>'Mesa del Tigre', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 82, "nombre"=>'San Pablo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 83, "nombre"=>'San José de Bolívar', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 84, "nombre"=>'Lobatera', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 84, "nombre"=>'Borotá', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 85, "nombre"=>'Michelena', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 86, "nombre"=>'Ureña', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 86, "nombre"=>'Aguas Calientes', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 87, "nombre"=>'San Josecito', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 88, "nombre"=>'Rubio', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 88, "nombre"=>'Río Chiquito', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 88, "nombre"=>'San Vicente de la Revancha', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 88, "nombre"=>'Bramón', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 89, "nombre"=>'Delicias', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 90, "nombre"=>'Colón', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 90, "nombre"=>'San Félix', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 90, "nombre"=>'San Pedro del Río', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 91, "nombre"=>'San Antonio del Táchira', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 91, "nombre"=>'El Recreo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 91, "nombre"=>'Palotal', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 91, "nombre"=>'Las Dantas', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 92, "nombre"=>'La Grita', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 92, "nombre"=>'Pueblo Hondo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 92, "nombre"=>'Sabana Grande', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 93, "nombre"=>'El Cobre', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 94, "nombre"=>'Seboruco', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 95, "nombre"=>'Santa Ana', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 96, "nombre"=>'San Rafael del Piñal', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 96, "nombre"=>'Puerto Teteo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 96, "nombre"=>'San Lorenzo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 97, "nombre"=>'Abejales', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 97, "nombre"=>'Puerto Nuevo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 97, "nombre"=>'San Joaquín de Navay', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 97, "nombre"=>'El Milagro', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 98, "nombre"=>'Pregonero', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 98, "nombre"=>'La Fundación', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 98, "nombre"=>'Laguna de García', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 98, "nombre"=>'Patio Redondo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 99, "nombre"=>'Capacho Nuevo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 99, "nombre"=>'Peribeca', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 99, "nombre"=>'El Valle', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 100, "nombre"=>'Capacho Viejo', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 100, "nombre"=>'Hato de la Virgen', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 100, "nombre"=>'El Pueblito', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 101, "nombre"=>'La Fría', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 101, "nombre"=>'Boca de Grita', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 101, "nombre"=>'Orope', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 102, "nombre"=>'Las Mesas', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 103, "nombre"=>'Coloncito', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 103, "nombre"=>'La Palmita', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 104, "nombre"=>'La Tendida', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 104, "nombre"=>'Boconó', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 104, "nombre"=>'Hernández', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 105, "nombre"=>'San Simón', "created_at" => now()],
        ["estado_id" => 6, "municipio_id" => 106, "nombre"=>'Umuquena', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 107, "nombre"=>'Urbana Bejuma', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 107, "nombre"=>'Canoabo', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 107, "nombre"=>'Chirgua', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 108, "nombre"=>'Urbana Güigüe', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 108, "nombre"=>'Central de Tacarigua', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 108, "nombre"=>'Belén', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 109, "nombre"=>'Urbana Mariara', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 110, "nombre"=>'Urbana Mariara', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 110, "nombre"=>'Urbana Guacara', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 110, "nombre"=>'Yagua', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 110, "nombre"=>'Guacara', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 111, "nombre"=>'Urbana Morón', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 111, "nombre"=>'Urama', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 112, "nombre"=>'Urbana Tocuyito', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 113, "nombre"=>'Urbana Los Guayos', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 114, "nombre"=>'Urbana Miranda', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 115, "nombre"=>'Urbana Montalbán', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 116, "nombre"=>'Urbana Naguanagua', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 117, "nombre"=>'Urbana Puerto Cabello', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 117, "nombre"=>'Borburata', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 117, "nombre"=>'Patanemo', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 118, "nombre"=>'Urbana San Diego', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 119, "nombre"=>'Urbana San Joaquín', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 120, "nombre"=>'Urbana Valencia', "created_at" => now()],
        ["estado_id" => 7, "municipio_id" => 120, "nombre"=>'Los Naranjos', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 121, "nombre"=>'Cojedes', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 121, "nombre"=>'Apartaderos', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 122, "nombre"=>'Tinaquillo', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 123, "nombre"=>'El Baúl', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 123, "nombre"=>'Sucre', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 124, "nombre"=>'Macapo', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 124, "nombre"=>'La Aguadita', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 125, "nombre"=>'El Pao', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 126, "nombre"=>'Libertad', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 126, "nombre"=>'El Amparo', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 127, "nombre"=>'Las Vegas', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 128, "nombre"=>'San Carlos', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 128, "nombre"=>'La Sierra', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 128, "nombre"=>'Manrique', "created_at" => now()],
        ["estado_id" => 8, "municipio_id" => 129, "nombre"=>'Tinaco', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 130, "nombre"=>'Barquisimeto', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 130, "nombre"=>'Bobare', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 130, "nombre"=>'Buena Vista', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 130, "nombre"=>'Río Claro', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 131, "nombre"=>'Río Claro', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 131, "nombre"=>'Sarare', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 131, "nombre"=>'Manzanita', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 131, "nombre"=>'La Miel', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'La Miel', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'EL Tocuyo', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'El Tocuyo', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'Barbacoas', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'Guaitó', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'Azoátegui', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'Villanueva', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'Guárico', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'Humocaro Alto', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 132, "nombre"=>'Humocaro Bajo', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 133, "nombre"=>'Cabudare', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 133, "nombre"=>'Los Rastrojos', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 133, "nombre"=>'Agua Viva', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 134, "nombre"=>'Agua Viva', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 134, "nombre"=>'Crespo', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 134, "nombre"=>'Duaca', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 134, "nombre"=>'El Eneal', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 135, "nombre"=>'Sanare', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 135, "nombre"=>'La Bucarita', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 135, "nombre"=>'La Escalera', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 136, "nombre"=>'Siquisique', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 136, "nombre"=>'Santa Inés', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 136, "nombre"=>'Aguada Grande', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 136, "nombre"=>'Baragua', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Carora', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Curarigua', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Río Tucuyo', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Atarigua', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'La Pastora', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Aregue', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Quebrada Arriba', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Arenales', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'San Pedro', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Burere', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'El Empedrado', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Palmarito', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'San Francisco', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'El Jabón', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Parapara', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 137, "nombre"=>'Altagracia', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 138, "nombre"=>'Quíbor', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 138, "nombre"=>'Quibor', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 138, "nombre"=>'Cubiro', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 138, "nombre"=>'Agua Negra', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 138, "nombre"=>'San Miguel', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 138, "nombre"=>'Tintorero', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 138, "nombre"=>'El Hato', "created_at" => now()],
        ["estado_id" => 9, "municipio_id" => 138, "nombre"=>'La Ceiba', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 139, "nombre"=>'Agua Blanca', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 140, "nombre"=>'Araure', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 140, "nombre"=>'Río Acarigua', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 141, "nombre"=>'Píritu', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 141, "nombre"=>'Uveral', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 142, "nombre"=>'Guanare', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 142, "nombre"=>'Córdoba', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 142, "nombre"=>'Mesa de Cavacas', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 142, "nombre"=>'Quebrada de la Virgen', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 142, "nombre"=>'San José de la Montaña', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 143, "nombre"=>'Guanarito', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 143, "nombre"=>'Trinidad de la Capilla', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 143, "nombre"=>'Morrones', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 144, "nombre"=>'Paraíso de Chabasquén', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 144, "nombre"=>'Peña Blanca', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 145, "nombre"=>'Ospino', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 145, "nombre"=>'La Aparición', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 145, "nombre"=>'la Estación', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 146, "nombre"=>'Acarigua', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 146, "nombre"=>'Payara', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 146, "nombre"=>'Mijagüito', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 146, "nombre"=>'Pimpinela', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 147, "nombre"=>'Papelón', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 147, "nombre"=>'Caño Delgadito', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 148, "nombre"=>'Boconoito', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 148, "nombre"=>'San Nicolás', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 149, "nombre"=>'San Rafael de Onoto', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 149, "nombre"=>'Santa Fe', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 149, "nombre"=>'El Algarrobito', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 150, "nombre"=>'El Playón', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 150, "nombre"=>'Nueva Florida', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 151, "nombre"=>'Biscucuy', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 151, "nombre"=>'La Concepción', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 151, "nombre"=>'San Rafael de Palo Alzado', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 151, "nombre"=>'Las Cruces', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 151, "nombre"=>'San Jose de Saguaz', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 151, "nombre"=>'Villa Rosa', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 152, "nombre"=>'Villa Bruzual', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 152, "nombre"=>'La Misión', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 152, "nombre"=>'Santa Cruz', "created_at" => now()],
        ["estado_id" => 10, "municipio_id" => 152, "nombre"=>'Colonia Turén', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 153, "nombre"=>'San Pablo', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 154, "nombre"=>'Aroa', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 155, "nombre"=>'Chivacoa', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 155, "nombre"=>'Campo Elías', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 156, "nombre"=>'Cocorote', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 157, "nombre"=>'Independencia', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 158, "nombre"=>'Sabana de Parra', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 159, "nombre"=>'Boraure', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 160, "nombre"=>'Yumare', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 161, "nombre"=>'Nirgua', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 161, "nombre"=>'Salom', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 161, "nombre"=>'Temerla', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 162, "nombre"=>'Yaritagua', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 162, "nombre"=>'Cambural', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 163, "nombre"=>'San Felipe', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 163, "nombre"=>'Marín', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 163, "nombre"=>'Albarico', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 164, "nombre"=>'Guama', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 165, "nombre"=>'Urachiche', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 166, "nombre"=>'Farriar', "created_at" => now()],
        ["estado_id" => 11, "municipio_id" => 166, "nombre"=>'Casimiro Vásquez', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 167, "nombre"=>'Puerto Ayacucho', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 167, "nombre"=>'Limón de Parhueña', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 167, "nombre"=>'Platanillal', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 168, "nombre"=>'Acanaña', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 168, "nombre"=>'Toky-Shamanaña', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 168, "nombre"=>'Mavaca', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 168, "nombre"=>'Parimabé', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 169, "nombre"=>'Laja Lisa', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 169, "nombre"=>'Macuruco', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 169, "nombre"=>'Guarinuma', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 170, "nombre"=>'Victorino', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 171, "nombre"=>'Samariapo', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 171, "nombre"=>'Pendare', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 171, "nombre"=>'Munduapo', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 171, "nombre"=>'San Pedro del Orinoco', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 172, "nombre"=>'Cacurí', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 172, "nombre"=>'Camani', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 172, "nombre"=>'Marueta', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 173, "nombre"=>'Solano', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 173, "nombre"=>'Curimacare', "created_at" => now()],
        ["estado_id" => 12, "municipio_id" => 173, "nombre"=>'Santa Lucía', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 174, "nombre"=>'San Fernando de Apure', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 174, "nombre"=>'El Recreo', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 174, "nombre"=>'Arichuna', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 174, "nombre"=>'San Rafael de Atamaica', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 175, "nombre"=>'Achaguas', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 175, "nombre"=>'El Yagual', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 175, "nombre"=>'Guachara', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 175, "nombre"=>'Guasimal', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 175, "nombre"=>'El Samán de Apure', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 176, "nombre"=>'San Juan de Payara', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 176, "nombre"=>'Puerto Páez', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 176, "nombre"=>'San Miguel de Cunaviche', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 177, "nombre"=>'Bruzual', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 177, "nombre"=>'Quintero', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 177, "nombre"=>'La Estacada', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 177, "nombre"=>'Mantecal', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 177, "nombre"=>' San Vicente', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 178, "nombre"=>'Biruaca', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 179, "nombre"=>'Guasdualito', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 179, "nombre"=>'Palmarito', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 179, "nombre"=>'El Amparo', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 179, "nombre"=>'El Nula', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 179, "nombre"=>'La Victoria', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 180, "nombre"=>'Elorza', "created_at" => now()],
        ["estado_id" => 13, "municipio_id" => 180, "nombre"=>'La Trinidad de Orichuna', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 181, "nombre"=>'Maracay', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 181, "nombre"=>'Choroní', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 182, "nombre"=>'Santa Rita', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 182, "nombre"=>'Francisco Miranda', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 182, "nombre"=>'Paraparal', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 183, "nombre"=>'El Limón', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 183, "nombre"=>'Caña de Azúcar', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 184, "nombre"=>'Turmero', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 184, "nombre"=>'Rosario de Paya', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 184, "nombre"=>'Chuao', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 184, "nombre"=>'San Joaquín', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 184, "nombre"=>'19 de Abril', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 185, "nombre"=>'Ocumare de La Costa', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 186, "nombre"=>'La Victoria', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 186, "nombre"=>'Las Mercedes', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 186, "nombre"=>'Las Guacamayas', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 186, "nombre"=>'Pao de Zárate', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 186, "nombre"=>'Zuata', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 187, "nombre"=>'San Mateo', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 188, "nombre"=>'El Consejo', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 189, "nombre"=>'La  Colonia Tovar', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 190, "nombre"=>'Villa de Cura', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 190, "nombre"=>'San Francisco de Asís', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 190, "nombre"=>'Los Bagres', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 190, "nombre"=>'Tocorón', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 190, "nombre"=>'Magdaleno', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 191, "nombre"=>'Cagua', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 191, "nombre"=>'Bella Vista', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 192, "nombre"=>'Santa Cruz', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 193, "nombre"=>'Palo Negro', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 193, "nombre"=>'La Pica', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 194, "nombre"=>'Camatagua', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 194, "nombre"=>'Carmen de Cura', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 195, "nombre"=>'San Casimiro', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 195, "nombre"=>'Güiripa', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 195, "nombre"=>'Ollas de Caramacate', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 195, "nombre"=>'Valle Morín', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 196, "nombre"=>'San Sebastián', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 197, "nombre"=>'Barbacoas', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 197, "nombre"=>'Las Peñitas', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 197, "nombre"=>'San Francisco de Cara', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 197, "nombre"=>'Taguay', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 198, "nombre"=>'Las Tejerías', "created_at" => now()],
        ["estado_id" => 14, "municipio_id" => 198, "nombre"=>'Tiara', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 199, "nombre"=>'San Juan de Los Morros', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 199, "nombre"=>'Cantagallo', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 199, "nombre"=>'Parapara', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 200, "nombre"=>'Calabozo', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 200, "nombre"=>'El Calvario', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 200, "nombre"=>'El Rastro', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 200, "nombre"=>'Guardatinajas', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 201, "nombre"=>'Valle de la Pascua', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 201, "nombre"=>'Espino', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 202, "nombre"=>'Chaguaramas', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 203, "nombre"=>'El Socorro', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 204, "nombre"=>'Las Mercedes', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 204, "nombre"=>'Cabruta', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 204, "nombre"=>'Santa Rita', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 205, "nombre"=>'Tucupido', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 205, "nombre"=>'San Rafael de Laya', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 206, "nombre"=>'Santa María de Ipire', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 206, "nombre"=>'Altamira', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 207, "nombre"=>'Altagracia de Orituco', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 207, "nombre"=>'Lezama', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 207, "nombre"=>'Libertad de Orituco', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 207, "nombre"=>'Paso Real de Macaira', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 207, "nombre"=>'San Francisco de Macaira', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 207, "nombre"=>'San Rafael de Orituco', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 207, "nombre"=>'Sabana Grande de Orituco', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 208, "nombre"=>'San José de Guaribe', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 209, "nombre"=>'Zaraza', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 209, "nombre"=>'san José de Unare', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 210, "nombre"=>'Ortíz', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 210, "nombre"=>'La Unión de Canuto', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 210, "nombre"=>'San Francisco de Tiznado', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 210, "nombre"=>'San José de Tiznado', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 211, "nombre"=>'Camaguán', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 211, "nombre"=>'Puerto Miranda', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 211, "nombre"=>'Uverito', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 212, "nombre"=>'Guayabal', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 212, "nombre"=>'Cazorla', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 213, "nombre"=>'El Sombrero', "created_at" => now()],
        ["estado_id" => 15, "municipio_id" => 213, "nombre"=>'Sosa', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 214, "nombre"=>'Santa Ana de Coro', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 214, "nombre"=>'La Negrita', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 214, "nombre"=>'Mitare', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 214, "nombre"=>'Río Seco', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 214, "nombre"=>'Sabaneta', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 215, "nombre"=>'Punto Fijo', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 215, "nombre"=>'Punta Cardón', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 215, "nombre"=>'Santa Ana', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 216, "nombre"=>'Pueblo Nuevo', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 216, "nombre"=>'Adícora', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 216, "nombre"=>'Baraived', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 216, "nombre"=>'Buena Vista', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 216, "nombre"=>'Jadacaquiva', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 216, "nombre"=>'Moruy', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 216, "nombre"=>'Adaure', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 216, "nombre"=>'El Hato', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 216, "nombre"=>'El Vínculo', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 217, "nombre"=>'La Vela de Coro', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 217, "nombre"=>'Acurigua', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 217, "nombre"=>' Guaibacoa', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 217, "nombre"=>'Las Calderas', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 217, "nombre"=>'El Moyepo', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 218, "nombre"=>'Puerto Cumarebo', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 218, "nombre"=>'La Ciénaga', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 218, "nombre"=>'La Soledad', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 218, "nombre"=>'Pueblo Cumarebo', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 218, "nombre"=>'Zazárida', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 219, "nombre"=>'Píritu', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 219, "nombre"=>'San José de la Costa', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 220, "nombre"=>'Tocópero', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 221, "nombre"=>'Tucacas', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 221, "nombre"=>'Boca de Aroa', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 222, "nombre"=>'Chichiriviche', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 222, "nombre"=>'Boca de Tocuyo', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 222, "nombre"=>'Tocuyo de la Costa', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 223, "nombre"=>'Tocuyo de la Costa', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 224, "nombre"=>'San Juan de los Cayos', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 224, "nombre"=>'Capadare', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 224, "nombre"=>'La Pastora', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 224, "nombre"=>'El Mene de San Lorenzo', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 225, "nombre"=>'Jacura', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 225, "nombre"=>'Agua Linda', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 225, "nombre"=>'Araurima', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 226, "nombre"=>'Yaracal', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 227, "nombre"=>'Palmasola', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 228, "nombre"=>'Santa Cruz de los Taques', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 228, "nombre"=>'Judibana', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 229, "nombre"=>'Churuguara', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 229, "nombre"=>'El Paují', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 229, "nombre"=>'El Tupí', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 229, "nombre"=>'Agua Larga', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 229, "nombre"=>'Mapararí', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 230, "nombre"=>'Santa Cruz de Bucaral', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 230, "nombre"=>'El Charal', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 230, "nombre"=>'Las Vegas del Tuy', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 231, "nombre"=>'Cabure', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 231, "nombre"=>'Pueblo Nuevo de La Sierra', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 231, "nombre"=>'Curimagua', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 232, "nombre"=>'Pedregal', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 232, "nombre"=>'El Manantial (Agua Clara)', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 232, "nombre"=>'Tupure', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 232, "nombre"=>'Piedra Grande', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 232, "nombre"=>'Purureche', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 233, "nombre"=>'San Luis', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 233, "nombre"=>'Aracua', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 233, "nombre"=>'La Peña', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 234, "nombre"=>'La Cruz de Taratara', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 234, "nombre"=>'Pecaya', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 235, "nombre"=>'Mene de Mauroa', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 235, "nombre"=>'Casigua', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 235, "nombre"=>'San Félix', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 236, "nombre"=>'Capatárida', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 236, "nombre"=>'Bariro', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 236, "nombre"=>'Borojó', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 236, "nombre"=>'Guajiro', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 236, "nombre"=>'San José de Seque', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 236, "nombre"=>'Zazárida', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 237, "nombre"=>'Dabajuro', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 238, "nombre"=>'Urumaco', "created_at" => now()],
        ["estado_id" => 16, "municipio_id" => 238, "nombre"=>'San José de Bruzual', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 239, "nombre"=>'Maracaibo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 239, "nombre"=>'San Isidro', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 239, "nombre"=>'Santa Lucía', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 240, "nombre"=>'Maracaibo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 240, "nombre"=>'San Francisco', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 240, "nombre"=>'El Bajo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 240, "nombre"=>'El Silencio', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 240, "nombre"=>'Sierra Maestra', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 240, "nombre"=>'Sur América', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 240, "nombre"=>'Los Cortijos', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 241, "nombre"=>'Cabimas', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 241, "nombre"=>'Palito Blanco', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 241, "nombre"=>'Punta Gorda', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 242, "nombre"=>'Santa Rita', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 242, "nombre"=>'El Mene', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 242, "nombre"=>'Palmarejo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 242, "nombre"=>'El Guanábano', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 243, "nombre"=>'Ciudad Ojeda', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 243, "nombre"=>'Campo Lara', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 243, "nombre"=>'Picapica', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 243, "nombre"=>'Lagunillas', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 244, "nombre"=>'Lagunillas', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 244, "nombre"=>'San Isidro', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 244, "nombre"=>'Sabana de La Plata', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 245, "nombre"=>'Tamare', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 245, "nombre"=>'La Sierrita', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 245, "nombre"=>'Las Parcelas', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 245, "nombre"=>'Carrasquero', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 245, "nombre"=>'Cachirí', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 245, "nombre"=>'Santa Cruz de Mara', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 246, "nombre"=>'Cojoro', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 246, "nombre"=>'El Molinete', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 246, "nombre"=>'Paraguaipoa', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 247, "nombre"=>'El Toro', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 247, "nombre"=>'San Carlos', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 248, "nombre"=>'San Carlos del Zulia', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 248, "nombre"=>'Santa Bárbara', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 248, "nombre"=>'Concha', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 249, "nombre"=>'Encontrados', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 249, "nombre"=>'El Guayabo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 250, "nombre"=>'Casigua El Cubo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 250, "nombre"=>'El Cruce', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 251, "nombre"=>'Gibraltar', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 251, "nombre"=>'San Antonio', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 251, "nombre"=>'Santa María', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 251, "nombre"=>'Caja Seca', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 252, "nombre"=>'Pueblo Nuevo El Chivo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 252, "nombre"=>'Cuatro Esquinas', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 252, "nombre"=>'Los Naranjos', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 253, "nombre"=>'Machiques', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 253, "nombre"=>'Las Piedras', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 253, "nombre"=>'Río Negro', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 253, "nombre"=>'San José', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 254, "nombre"=>'La Concepción', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 254, "nombre"=>'La Paz', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 254, "nombre"=>'Jobo Alto (Kilómetro 25)', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 254, "nombre"=>'San José', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 255, "nombre"=>'La Concepción', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 255, "nombre"=>'Kilómetro 48 (Santo Domingo)', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 255, "nombre"=>'La Ensenada', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 255, "nombre"=>'El Carmelo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 255, "nombre"=>'Potreritos', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 256, "nombre"=>' Los Puertos de Altagracia', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 256, "nombre"=>'El Mecocal', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 256, "nombre"=>'Quisiro', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 256, "nombre"=>'El Consejo de Ciruma', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 256, "nombre"=>'Sabaneta de Palmas', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 257, "nombre"=>'San Timoteo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 257, "nombre"=>'Ceuta', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 257, "nombre"=>'Mene Grande', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 257, "nombre"=>'El Venado', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 257, "nombre"=>'El Tigre', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 257, "nombre"=>'Pueblo Nuevo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 258, "nombre"=>'Bachaquero', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 258, "nombre"=>'El Corozo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 259, "nombre"=>'El Corozo', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 259, "nombre"=>'La Villa del Rosario', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 259, "nombre"=>'Barranquitas', "created_at" => now()],
        ["estado_id" => 17, "municipio_id" => 259, "nombre"=>'San Ignacio', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 260, "nombre"=>'Barcelona', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 260, "nombre"=>'Bergantín', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 260, "nombre"=>'Caigua', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 260, "nombre"=>'El Pilar', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 260, "nombre"=>'Naricual', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 261, "nombre"=>'Aragua de Barcelona', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 261, "nombre"=>'Cachipo', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 262, "nombre"=>'Anaco', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 262, "nombre"=>'San Joaquín', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 263, "nombre"=>'Boca de Chávez', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 264, "nombre"=>'Cantaura', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 264, "nombre"=>'Santa Rosa', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 264, "nombre"=>'Urica', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 265, "nombre"=>'Clarines', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 266, "nombre"=>'Valle de Guanape', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 266, "nombre"=>'Santa Bárbara', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 267, "nombre"=>'Soledad', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 267, "nombre"=>'Carapa', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 268, "nombre"=>'Guanta', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 268, "nombre"=>'Pertigalete', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 269, "nombre"=>'Lecherías', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 270, "nombre"=>'Onoto', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 270, "nombre"=>'San Pablo', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 271, "nombre"=>'Puerto Píritu', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 271, "nombre"=>'San Miguel', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 271, "nombre"=>'El Hatillo', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 272, "nombre"=>'Píritu', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 272, "nombre"=>'San Francisco', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 273, "nombre"=>'Puerto La Cruz', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 273, "nombre"=>'Pozuelos', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 273, "nombre"=>'Guanape', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 274, "nombre"=>'Santa Ana', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 274, "nombre"=>'Pueblo Nuevo', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 275, "nombre"=>'San Mateo', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 275, "nombre"=>'El Carito', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 275, "nombre"=>'Santa Inés', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 276, "nombre"=>'El Tigre', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 277, "nombre"=>'El Chaparro', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 277, "nombre"=>'José Gregorio Monagas', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 278, "nombre"=>'Pariaguán', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 278, "nombre"=>'Atapirire', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 278, "nombre"=>'Boca del Pao', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 278, "nombre"=>'El Pao de Barcelona', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 279, "nombre"=>'San José de Guanipa (El Tigrito)', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 280, "nombre"=>'Mapire', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 280, "nombre"=>'Santa Cruz de Orinoco', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 280, "nombre"=>'San Diego de Cabrutica', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 280, "nombre"=>'Santa Clara', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 280, "nombre"=>'Uverito', "created_at" => now()],
        ["estado_id" => 18, "municipio_id" => 280, "nombre"=>'Zuata', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 281, "nombre"=>'Ciudad Bolívar', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 281, "nombre"=>'Almacén', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 281, "nombre"=>'San José de Bongo', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 281, "nombre"=>'La Carolina', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 282, "nombre"=>'Maripa', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 282, "nombre"=>'Aripao', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 282, "nombre"=>'Guarataro', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 282, "nombre"=>'Las Majadas', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 282, "nombre"=>'Moitaco', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 283, "nombre"=>'Ciudad Piar', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 283, "nombre"=>'La Paragua', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 283, "nombre"=>'San Francisco', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 283, "nombre"=>'Santa Bárbara de Centurión', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 284, "nombre"=>'Santa Bárbara de Centurión', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 284, "nombre"=>'Caicara del Orinoco', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 284, "nombre"=>'Las Bonitas', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 284, "nombre"=>'Santa Rosalía', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 284, "nombre"=>'El Milagro', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 284, "nombre"=>'La Urbana', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 284, "nombre"=>'Morichalito', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 285, "nombre"=>'Santa Elena de Uairén', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 285, "nombre"=>'Ikabarú', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 286, "nombre"=>'El Palmar', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 287, "nombre"=>'Ciudad Guayana', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 287, "nombre"=>'Pozo Verde', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 287, "nombre"=>'El Rosario', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 288, "nombre"=>'Upata', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 288, "nombre"=>'El Manteco', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 289, "nombre"=>'Guasipati', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 289, "nombre"=>'El Miamo', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 290, "nombre"=>'El Callao', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 291, "nombre"=>'Tumeremo', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 291, "nombre"=>'El Dorado', "created_at" => now()],
        ["estado_id" => 19, "municipio_id" => 291, "nombre"=>'Las Claritas', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 292, "nombre"=>'Curiapo', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 292, "nombre"=>'Manoa', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 292, "nombre"=>'Boca de Cuyubini', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 292, "nombre"=>'Araguabisi', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 292, "nombre"=>'San Francisco de Guayo', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 292, "nombre"=>'Araguaimujo', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 293, "nombre"=>'Sierra Imataca', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 293, "nombre"=>'Moruca', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 293, "nombre"=>'Piacoa', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 293, "nombre"=>'El Triunfo', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 293, "nombre"=>'Santa Catalina', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 294, "nombre"=>'Perdenales', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 294, "nombre"=>'Capure', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 295, "nombre"=>'Tucupita', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 295, "nombre"=>'Hacienda del Medio', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 295, "nombre"=>'Carapal de Guara', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 295, "nombre"=>'Urbanización Leonardo Ruiz Pineda', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 295, "nombre"=>'Paloma', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 295, "nombre"=>'Urbanización Delfín Mendoza', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 295, "nombre"=>'San Rafael', "created_at" => now()],
        ["estado_id" => 20, "municipio_id" => 295, "nombre"=>'La Horqueta', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 296, "nombre"=>'San Antonio', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 296, "nombre"=>'San Francisco', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 297, "nombre"=>'Aguasay', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 298, "nombre"=>'Caripito', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 299, "nombre"=>'Caripe', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 299, "nombre"=>'El Guácharo', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 299, "nombre"=>'La Guanota', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 299, "nombre"=>'Sabana de Piedra', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 299, "nombre"=>'San Agustín', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 299, "nombre"=>'Teresén', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 300, "nombre"=>'Caicara', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 300, "nombre"=>'Areo', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 300, "nombre"=>'San Félix', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 300, "nombre"=>'Viento Fresco', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 301, "nombre"=>'Punta de Mata', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 301, "nombre"=>'El Tejero', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 302, "nombre"=>'Temblador', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 302, "nombre"=>'Chaguaramas', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 302, "nombre"=>'Las Alhuacas', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 302, "nombre"=>'Tabasca', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 303, "nombre"=>'Maturín', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 303, "nombre"=>'El Corozo', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 303, "nombre"=>'El Furrial', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 303, "nombre"=>'Jusepín', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 303, "nombre"=>'La Pica', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 303, "nombre"=>'San Vicente', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 304, "nombre"=>'Aragua', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 304, "nombre"=>'Aparicio', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 304, "nombre"=>'Chaguaramal', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 304, "nombre"=>'El Pinto', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 304, "nombre"=>'Guanaguana', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 304, "nombre"=>'La Toscana', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 304, "nombre"=>'Taguaya', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 305, "nombre"=>'Quiriquire', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 305, "nombre"=>'Cachipo', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 306, "nombre"=>'Santa Bárbara', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 307, "nombre"=>'Barrancas', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 307, "nombre"=>'Los Barrancos de Fajardo', "created_at" => now()],
        ["estado_id" => 21, "municipio_id" => 308, "nombre"=>'Uracoa', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 309, "nombre"=>'La Plaza de Paraguachí', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 310, "nombre"=>'La Asunción', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 311, "nombre"=>'San Juan Bautista', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 311, "nombre"=>'La Guardia', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 312, "nombre"=>'El Valle del Espíritu Santo', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 312, "nombre"=>'Villa Rosa', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 313, "nombre"=>'Porlamar', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 314, "nombre"=>'Santa Ana', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 314, "nombre"=>'El Maco', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 314, "nombre"=>'Tacarigua', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 314, "nombre"=>'Pedro González', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 314, "nombre"=>'Altagracia', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 315, "nombre"=>'Pampatar', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 315, "nombre"=>'El Pilar (Los Robles)', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 316, "nombre"=>'Juangriego', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 316, "nombre"=>'Los Millanes', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 317, "nombre"=>'Boca del Río', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 317, "nombre"=>'Boca del Pozo', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 318, "nombre"=>'Punta de Piedras', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 318, "nombre"=>'El Guamache', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 319, "nombre"=>'San Pedro de Coche', "created_at" => now()],
        ["estado_id" => 22, "municipio_id" => 319, "nombre"=>'Güinima', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 320, "nombre"=>'Cumaná', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 320, "nombre"=>'Caigüire', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 320, "nombre"=>'San Juan', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 320, "nombre"=>'Los Puertos de Santa Fe', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 320, "nombre"=>'Los Altos de Sucre', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 321, "nombre"=>'Araya', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 321, "nombre"=>'Chacopata', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 321, "nombre"=>'Manicuare', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 322, "nombre"=>'Cumanacoa', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 322, "nombre"=>'Arenas', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 322, "nombre"=>'Acarigua', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 322, "nombre"=>'Las Piedras', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 322, "nombre"=>'Villarroel (Quebrada Seca)', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 322, "nombre"=>'San Lorenzo', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 323, "nombre"=>'Marigüitar', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 324, "nombre"=>'San Antonio de Golfo', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 325, "nombre"=>'Cariaco', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 325, "nombre"=>'Catuaro', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 325, "nombre"=>'Muelle de Cariaco', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 325, "nombre"=>'Santa Cruz', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 325, "nombre"=>'Santa María', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 326, "nombre"=>'Playa Grande', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 326, "nombre"=>'Carúpano', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 327, "nombre"=>'El Pilar', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 327, "nombre"=>'El Rincón', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 327, "nombre"=>'Los Arroyos', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 327, "nombre"=>'Guaraúnos', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 327, "nombre"=>'Tunapuicito', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 327, "nombre"=>'Guariquén', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 328, "nombre"=>'Tunapuy', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 328, "nombre"=>'Guayana', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 329, "nombre"=>'Yaguaraparo', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 329, "nombre"=>'El Paujil', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 329, "nombre"=>'Río Seco', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 330, "nombre"=>'Irapa', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 330, "nombre"=>'Campo Claro', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 330, "nombre"=>'Marabal', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 330, "nombre"=>'San Antonio de Irapa', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 330, "nombre"=>'Soro', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 331, "nombre"=>'Güiria', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 331, "nombre"=>'Río Salado', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 331, "nombre"=>'Macuro', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 331, "nombre"=>'Yoco', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 332, "nombre"=>'Río Caribe', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 332, "nombre"=>'San Juan de Unare', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 332, "nombre"=>'El Morro de Puerto Santo', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 332, "nombre"=>'Puerto Santo', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 332, "nombre"=>'San Juan de Las Galdonas', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 333, "nombre"=>'San José de Aerocuar', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 333, "nombre"=>'Río Casanay', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 334, "nombre"=>'Casanay', "created_at" => now()],
        ["estado_id" => 23, "municipio_id" => 334, "nombre"=>'San Vicente', "created_at" => now()],
        ["estado_id" => 24, "municipio_id" => 335, "nombre"=>'La Guaira', "created_at" => now()],
        ["estado_id" => 24, "municipio_id" => 335, "nombre"=>'Maiquetía', "created_at" => now()],
        ["estado_id" => 24, "municipio_id" => 335, "nombre"=>'Catia La Mar', "created_at" => now()],
        ["estado_id" => 24, "municipio_id" => 335, "nombre"=>'Macuto', "created_at" => now()],
        ["estado_id" => 24, "municipio_id" => 335, "nombre"=>'Caraballeda', "created_at" => now()],
        ["estado_id" => 24, "municipio_id" => 335, "nombre"=>'Naiguatá', "created_at" => now()],
        ["estado_id" => 24, "municipio_id" => 335, "nombre"=>'Carayaca', "created_at" => now()],
        ["estado_id" => 24, "municipio_id" => 335, "nombre"=>'La Sabana', "created_at" => now()],

        ]);
    }
}
