<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('municipios')->insert([


        ["estado_id" => 1, "nombre"=> 'Libertador', "activo" => true, "created_at" => now()],

        ["estado_id" => 2, "nombre" => 'Chacao', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Baruta', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'El Hatillo', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Guaicaipuro', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Carrizal', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Los Salias', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Lander', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Cristóbal Rojas', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Urdaneta', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Simón Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Paz Castillo', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Independencia', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Plaza', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Zamora', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Buroz', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Brión', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Andrés Bello', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Páez', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Pedro Gual', "activo" => true, "created_at" => now()],
        ["estado_id" => 2, "nombre" => 'Acevedo', "activo" => true, "created_at" => now()],

        ["estado_id" => 3, "nombre" => 'Barinas', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Alberto Arvelo Torrealba', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Sosa', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Antonio José de Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Arismendi', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Rojas', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Cruz Paredes', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Ezequiel Zamora', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Andrés Eloy Blanco', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Obispos', "activo" => true, "created_at" => now()],
        ["estado_id" => 3, "nombre" => 'Pedraza', "activo" => true, "created_at" => now()],

        ["estado_id" => 4, "nombre" => 'Trujillo', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Valera', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Escuque', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Motatán', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Pampanito', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Rafael Rangel', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'San Rafael de Carvajal', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Boconó', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Juan Vicente Campo Elías', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Pampán', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'José Felipe Márquez Cañizales', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Candelaria', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Carache', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Miranda', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Andrés Bello', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Monte Carmelo', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'Urdaneta', "activo" => true, "created_at" => now()],
        ["estado_id" => 4, "nombre" => 'La Ceiba', "activo" => true, "created_at" => now()],

        ["estado_id" => 5, "nombre" => 'Libertador', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Alberto Adriani', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Andrés Bello', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Padre Noguera', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Pueblo Llano', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Rangel', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Rivas Dávila', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Santos Marquina', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Tovar', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Guaraque', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Zea', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Antonio Pinto Salinas', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Aricagua', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Arzobispo Chacón', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Campo Elías', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Obispo Ramos de Lora', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Caracciolo Parra Olmedo', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Cardenal Quintero', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Julio César Salas', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Justo Briceño', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Tulio Febres Cordero', "activo" => true, "created_at" => now()],
        ["estado_id" => 5, "nombre" => 'Miranda', "activo" => true, "created_at" => now()],

        ["estado_id" => 6, "nombre" => 'San Cristóbal', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Cárdenas', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Andrés Bello', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Guásimos', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Francisco de Miranda', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Lobatera', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Michelena', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Pedro María Ureña', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Torbes', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Junín', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Rafael Urdaneta', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Ayacucho', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Jáuregui', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'José María Vargas', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Seboruco', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Córdoba', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Fernández Feo', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Libertador', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Uribante', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Independencia', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Libertad', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'García de Hevia', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Antonio Rómulo Costa', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Panamericano', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Samuel Darío Maldonado', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'Simón Rodríguez', "activo" => true, "created_at" => now()],
        ["estado_id" => 6, "nombre" => 'San Judas Tadeo', "activo" => true, "created_at" => now()],

        ["estado_id" => 7, "nombre" => 'Bejuma', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Carlos Arvelo', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Diego Ibarra', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Guacara', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Juan José Mora', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Libertador', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Los Guayos', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Miranda', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Montalbán', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Naguanagua', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Puerto Cabello', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'San Diego', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'San Joaquín', "activo" => true, "created_at" => now()],
        ["estado_id" => 7, "nombre" => 'Valencia', "activo" => true, "created_at" => now()],

        ["estado_id" => 8, "nombre" => 'Anzoátegui', "activo" => true, "created_at" => now()],
        ["estado_id" => 8, "nombre" => 'Falcón', "activo" => true, "created_at" => now()],
        ["estado_id" => 8, "nombre" => 'Girardot', "activo" => true, "created_at" => now()],
        ["estado_id" => 8, "nombre" => 'Lima Blanco', "activo" => true, "created_at" => now()],
        ["estado_id" => 8, "nombre" => 'Pao de San Juan Bautista', "activo" => true, "created_at" => now()],
        ["estado_id" => 8, "nombre" => 'Ricaurte', "activo" => true, "created_at" => now()],
        ["estado_id" => 8, "nombre" => 'Rómulo Gallegos', "activo" => true, "created_at" => now()],
        ["estado_id" => 8, "nombre" => 'San Carlos', "activo" => true, "created_at" => now()],
        ["estado_id" => 8, "nombre" => 'Tinaco', "activo" => true, "created_at" => now()],

        ["estado_id" => 9, "nombre" => 'Iribarren', "activo" => true, "created_at" => now()],
        ["estado_id" => 9, "nombre" => 'Simón Planas', "activo" => true, "created_at" => now()],
        ["estado_id" => 9, "nombre" => 'Morán', "activo" => true, "created_at" => now()],
        ["estado_id" => 9, "nombre" => 'Palavecino', "activo" => true, "created_at" => now()],
        ["estado_id" => 9, "nombre" => 'Crespo', "activo" => true, "created_at" => now()],
        ["estado_id" => 9, "nombre" => 'Andrés Eloy Blanco', "activo" => true, "created_at" => now()],
        ["estado_id" => 9, "nombre" => 'Urdaneta', "activo" => true, "created_at" => now()],
        ["estado_id" => 9, "nombre" => 'Torres', "activo" => true, "created_at" => now()],
        ["estado_id" => 9, "nombre" => 'Jiménez', "activo" => true, "created_at" => now()],

        ["estado_id" => 10, "nombre" => 'Agua Blanca', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Araure', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Esteller', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Guanare', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Guanarito', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Monseñor José Vicente de Unda', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Ospino', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Páez', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Papelón', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'San Génaro de Boconoito', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'San Rafael de Onoto', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Santa Rosalía', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 10, "nombre" => 'Turén', "activo" => true, "created_at" => now()],

        ["estado_id" => 11, "nombre" => 'Arístides Bastidas', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Bruzual', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Cocorote', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Independencia', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'José Antonio Páez', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'La Trinidad', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Manuel Monge', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Nirgua', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Peña', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'San Felipe', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Urachiche', "activo" => true, "created_at" => now()],
        ["estado_id" => 11, "nombre" => 'Veroes', "activo" => true, "created_at" => now()],

        ["estado_id" => 12, "nombre" => 'Autónomo Atures', "activo" => true, "created_at" => now()],
        ["estado_id" => 12, "nombre" => 'Autónomo Alto Orinoco', "activo" => true, "created_at" => now()],
        ["estado_id" => 12, "nombre" => 'Autónomo Atabapo', "activo" => true, "created_at" => now()],
        ["estado_id" => 12, "nombre" => 'Autónomo Maroa', "activo" => true, "created_at" => now()],
        ["estado_id" => 12, "nombre" => 'Autónomo Autana', "activo" => true, "created_at" => now()],
        ["estado_id" => 12, "nombre" => 'Autónomo Manapiare', "activo" => true, "created_at" => now()],
        ["estado_id" => 12, "nombre" => 'Autónomo Río Negro', "activo" => true, "created_at" => now()],

        ["estado_id" => 13, "nombre" => 'San Fernando', "activo" => true, "created_at" => now()],
        ["estado_id" => 13, "nombre" => 'Achaguas', "activo" => true, "created_at" => now()],
        ["estado_id" => 13, "nombre" => 'Pedro Camejo', "activo" => true, "created_at" => now()],
        ["estado_id" => 13, "nombre" => 'Muñoz', "activo" => true, "created_at" => now()],
        ["estado_id" => 13, "nombre" => 'Biruaca', "activo" => true, "created_at" => now()],
        ["estado_id" => 13, "nombre" => 'Páez', "activo" => true, "created_at" => now()],
        ["estado_id" => 13, "nombre" => 'Rómulo Gallegos', "activo" => true, "created_at" => now()],

        ["estado_id" => 14, "nombre" => 'Girardot', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Francisco Linares Alcántara', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Mario Briceño Iragorry', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Santiago Mariño', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Ocumare de La Costa de Oro', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'José Félix Ribas', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'José Rafael Revenga', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Tovar', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Zamora', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'José Angel Lamas', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Libertador', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Camatagua', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'San Casimiro', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'San Sebastián', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Urdaneta', "activo" => true, "created_at" => now()],
        ["estado_id" => 14, "nombre" => 'Santos Michelena', "activo" => true, "created_at" => now()],

        ["estado_id" => 15, "nombre" => 'Juan Germán Roscio', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'Francisco de Miranda', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'Leonardo Infante', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'Chaguaramas', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'El Socorro', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'Las Mercedes', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'José Félix Ribas', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'Santa María de Ipire', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'José Tadeo Monagas', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'San José de Guaribe', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'Pedro Zaraza', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'Ortíz', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'Camaguán', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'San Gerónimo de Guayabal', "activo" => true, "created_at" => now()],
        ["estado_id" => 15, "nombre" => 'Julián Mellado', "activo" => true, "created_at" => now()],

        ["estado_id" => 16, "nombre" => 'Miranda', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Carirubana', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Falcón', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Colina', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Zamora', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Píritu', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Tocópero', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Silva', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Monseñor Iturriza', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'San Francisco', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Acosta', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Jacura', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Cacique Manaure', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Palmasola', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Los Taques', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Federación', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Unión', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Petit', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Democracia', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Mauroa', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Buchivacoa', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Dabajuro', "activo" => true, "created_at" => now()],
        ["estado_id" => 16, "nombre" => 'Urumaco', "activo" => true, "created_at" => now()],

        ["estado_id" => 17, "nombre" => 'Maracaibo', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'San Francisco', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Cabimas', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Santa Rita', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Lagunillas', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Simón Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Mara', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Indigena Bolivariano Guajira', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Almirante Padilla', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Colón', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Catatumbo', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Jesús María Semprún', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Francisco Javier Pulgar', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Machiques de Perijá', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Jesús Enrique Lossada', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'La Cañada de Urdaneta', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Miranda', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Baralt', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Valmore Rodríguez', "activo" => true, "created_at" => now()],
        ["estado_id" => 17, "nombre" => 'Rosario de Perijá', "activo" => true, "created_at" => now()],

        ["estado_id" => 18, "nombre" => 'Simón Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Aragua', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Anaco', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'San Juan de Capistrano', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Pedro María Freites', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Manuel Ezequiel Bruzual', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Francisco del Carmen Carvajal', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Independencia', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Guanta', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Turístico Diego Bautista Urbaneja', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Juan Manuel Cajigal', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Fernando de Peñalver', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Píritu', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Juan Antonio Sotillo', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Santa Ana', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Libertad', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Simón Rodríguez', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Sir Arthur Mc Gregor', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'Francisco de Miranda', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'San José de Guanipa', "activo" => true, "created_at" => now()],
        ["estado_id" => 18, "nombre" => 'José Gregorio Monagas', "activo" => true, "created_at" => now()],

        ["estado_id" => 19, "nombre" => 'Heres', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'Bolivariano Angostura', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'Cedeño', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'Gran Sabana', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'Padre Pedro Chien', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'Caroní', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'Piar', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'Roscio', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'El Callao', "activo" => true, "created_at" => now()],
        ["estado_id" => 19, "nombre" => 'Sifontes', "activo" => true, "created_at" => now()],
        ["estado_id" => 20, "nombre" => 'Antonio Díaz', "activo" => true, "created_at" => now()],

        ["estado_id" => 20, "nombre" => 'Casacoima', "activo" => true, "created_at" => now()],
        ["estado_id" => 20, "nombre" => 'Pedernales', "activo" => true, "created_at" => now()],
        ["estado_id" => 20, "nombre" => 'Tucupita', "activo" => true, "created_at" => now()],

        ["estado_id" => 21, "nombre" => 'Acosta', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Aguasay', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Caripe', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Cedeño', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Ezequiel Zamora', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Libertador', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Maturín', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Piar', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Púnceres', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Santa Bárbara', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Sotillo', "activo" => true, "created_at" => now()],
        ["estado_id" => 21, "nombre" => 'Uracoa', "activo" => true, "created_at" => now()],

        ["estado_id" => 22, "nombre" => 'Antolín del Campo', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'Arismendi', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'Díaz', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'García', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'Mariño', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'Gómez', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'Maneiro', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'Marcano', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'Península de Macanao', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'Tubores', "activo" => true, "created_at" => now()],
        ["estado_id" => 22, "nombre" => 'Villalba', "activo" => true, "created_at" => now()],

        ["estado_id" => 23, "nombre" => 'Sucre', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Cruz Salmerón Acosta', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Montes', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Bolívar', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Mejía', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Ribero', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Bermúdez', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Benítez', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Libertador', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Cajigal', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Mariño', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Valdez', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Arismendi', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Andrés Mata', "activo" => true, "created_at" => now()],
        ["estado_id" => 23, "nombre" => 'Andrés Eloy Blanco', "activo" => true, "created_at" => now()],

        ["estado_id" => 24, "nombre" => 'Vargas', "activo" => true, "created_at" => now()],






        ]);
    }

}
