<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paises = [

            ['continente_id' => '1', 'nombre' => 'Argelia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Angola', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Benín', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Botsuana', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Burkina Faso', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Burundi', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Camerún', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Cabo Verde', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'República Centroafricana', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Chad', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Comoras', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Congo (Rep.)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Costa de Marfil (Rep.)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'República Democrática del Congo', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Yibuti', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Egipto', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Guinea Ecuatorial', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Eritrea', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Esuatini', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Etiopía', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Gabón', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Gambia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Ghana', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Guinea', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Guinea-Bisáu', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Kenia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Lesoto', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Liberia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Madagascar', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Malaui', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Malí', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Mauritania', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Mauricio', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Marruecos', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Mozambique', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Namibia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Níger', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Nigeria', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Ruanda', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Santo Tomé y Príncipe', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Senegal', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Seychelles', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Sierra Leona', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Somalia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Sudáfrica', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Sudán del Sur (Rep.)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Estado de Libia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Sudán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Tanzania (Rep. Unida)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Togo', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Túnez', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Uganda', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Zambia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '1', 'nombre' => 'Zimbabue', 'activo' => true, "created_at" => now()],

            ['continente_id' => '2', 'nombre' => 'Antigua y Barbuda', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Argentina', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Aruba, Curazao y Sint Maarten', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Bahamas', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Barbados', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Belice', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Bolivia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Brasil', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Canadá', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Chile', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Colombia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Costa Rica', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Cuba', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Dominica', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'República Dominicana', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Ecuador', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'El Salvador', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Granada', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Guatemala', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Guyana', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Haití', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Honduras (Rep.)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Jamaica', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'México', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Nicaragua', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Panamá (Rep.)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Paraguay', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Perú', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'San Cristóbal y Nieves', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Santa Lucía', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'San Vicente y las Granadinas', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Surinam', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Trinidad y Tobago', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Estados Unidos de América', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Uruguay', 'activo' => true, "created_at" => now()],
            ['continente_id' => '2', 'nombre' => 'Venezuela', 'activo' => true, "created_at" => now()],

            ['continente_id' => '3', 'nombre' => 'Afganistán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Armenia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Azerbaiyán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Baréin', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Bangladés', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Bután', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Brunéi Darussalam', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Camboya', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'China (República Popular)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Chipre', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'República Popular Democrática de Corea', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Georgia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'India', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Indonesia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Irán (República Islámica)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Iraq', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Israel', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Japón', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Jordania', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Kazajistán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Corea (República)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Kuwait', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Kirguistán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'República Democrática Popular Lao', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Líbano', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Malasia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Maldivas', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Mongolia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Myanmar', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Nepal', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Omán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Pakistán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Filipinas', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Catar', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Arabia Saudita', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Singapur', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Sri Lanka', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'República Árabe Siria', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Tayikistán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Tailandia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Timor-Leste (República Democrática)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Turquía', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Turkmenistán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Emiratos Árabes Unidos', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Uzbekistán', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Vietnam', 'activo' => true, "created_at" => now()],
            ['continente_id' => '3', 'nombre' => 'Yemen', 'activo' => true, "created_at" => now()],

            ['continente_id' => '4', 'nombre' => 'Albania', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Austria', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Bielorrusia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Bélgica', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Bosnia y Herzegovina', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Bulgaria (Rep.)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Croacia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Chequia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Dinamarca', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Estonia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Finlandia (incluidas las Islas Åland)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Francia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Alemania', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Grecia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Hungría', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Islandia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Irlanda', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Italia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Letonia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Liechtenstein', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Lituania', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Luxemburgo', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Malta', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Moldavia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Mónaco', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Montenegro (Rep.)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Países Bajos', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Macedonia del Norte', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Noruega', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Territorios de Ultramar (Reino Unido de Gran Bretaña e Irlanda del Norte)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Polonia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Portugal', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Rumanía', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Federación Rusa', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'San Marino', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Serbia (Rep.)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Eslovaquia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Eslovenia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'España', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Suecia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Suiza', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Ucrania', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Reino Unido de Gran Bretaña e Irlanda del Norte', 'activo' => true, "created_at" => now()],
            ['continente_id' => '4', 'nombre' => 'Vaticano', 'activo' => true, "created_at" => now()],

            ['continente_id' => '5', 'nombre' => 'Australia', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Fiyi', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Kiribati', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Nauru', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Nueva Zelanda (incluida la Dependencia de Ross)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Papúa Nueva Guinea', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Samoa', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Islas Salomón', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Tonga (incluido Niuafo’ou)', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Tuvalu', 'activo' => true, "created_at" => now()],
            ['continente_id' => '5', 'nombre' => 'Vanuatu', 'activo' => true, "created_at" => now()],

        ];

        foreach ($paises as $pais) {
            Pais::firstOrCreate(
                ['continente_id' => $pais['continente_id'], 'nombre' => $pais['nombre']],
                ['activo' => true, 'created_at' => now()]
            );
        }
}}
